# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgWRacfrHHQZ8Zwn9HK9kRw-m-DeERdw
"""

pip install dash --upgrade

import dash
from dash import dcc, html  # Updated import statements
from dash.dependencies import Input, Output, State
import plotly.graph_objs as go
import numpy as np

# Define the layout of the dashboard
app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1('Projectile Trajectory Simulation'),
    html.Div([
        html.Label('Initial Velocity (m/s):'),
        dcc.Input(id='velocity', type='number', value=10)
    ]),
    html.Div([
        html.Label('Angle of Projection (degrees):'),
        dcc.Input(id='angle', type='number', value=45)
    ]),
    html.Div([
        html.Label('Gravity (m/s^2):'),
        dcc.Input(id='gravity', type='number', value=9.81)
    ]),
    html.Button('Simulate', id='simulate-button', n_clicks=0),
    dcc.Graph(id='trajectory-graph')
])

# Define the callback function to update the graph
@app.callback(
    Output('trajectory-graph', 'figure'),
    Input('simulate-button', 'n_clicks'),
    State('velocity', 'value'),
    State('angle', 'value'),
    State('gravity', 'value')
)
def update_graph(n_clicks, velocity, angle, gravity):
    # Convert angle to radians
    angle_rad = np.deg2rad(angle)

    # Calculate time of flight
    t_flight = 2 * velocity * np.sin(angle_rad) / gravity

    # Generate time array
    t = np.linspace(0, t_flight, 100)

    # Calculate x and y coordinates
    x = velocity * np.cos(angle_rad) * t
    y = velocity * np.sin(angle_rad) * t - 0.5 * gravity * t**2

    # Create the figure
    fig = go.Figure(data=[go.Scatter(x=x, y=y, mode='lines')])
    fig.update_layout(title='Projectile Trajectory',
                      xaxis_title='Horizontal Distance (m)',
                      yaxis_title='Height (m)')

    return fig

# Run the app
if __name__ == '__main__':
    app.run(debug=True)  # Updated method to run the app